### ISSUE TITLE
had to install differently

### ISSUE THREAD

**Issue by rseymour** [explosion/spacy-dev-resources#14]
I used the following command to install:

`
jupyter nbextension install https://raw.githubusercontent.com/explosion/spacy-dev-resources/master/jupyter-displacy/displacy.js`

**Comment by ines** [comment]
Thanks! That's interesting – did Jupyter throw an error when using the directory path?

I remember testing it with the directory and it worked for me, and I figured it'd need this to access the plugin meta data etc... but if the installation doesn't always work that way, I guess I need to fix something here.

**Comment by rseymour** [comment]
It didn't throw an error, it just wouldn't verify.  What it did was download the index.html and save it as jupiter-displacy with no extension.

**Comment by GruffPrys** [comment]
Thanks for the extension Ines, it works great now that I've followed rseymour's installation method to get it working.

Here are the details in case they help you fix it for others:

<details>
C:\Users\user>jupyter nbextension install https://github.com/explosion/spacy-dev-resources/tree/master/jupyter-displacy
  
Downloading: https://github.com/explosion/spacy-dev-resources/tree/master/jupyter-displacy -> C:\Users\user\AppData\Local\Temp\tmpz4fodyox\jupyter-displacy

Out of date: C:\ProgramData\jupyter\nbextensions\jupyter-displacy  

Copying: C:\Users\user\AppData\Local\Temp\tmpz4fodyox\jupyter-displacy -> C:\ProgramData\jupyter\nbextensions\jupyter-displacy  

To initialize this nbextension in the browser every time the notebook (or other app) loads:

jupyter nbextension enable <the entry point>


C:\Users\user>jupyter nbextension enable displacy  
Enabling notebook extension displacy...  
      - Validating: problems found:  
        - require?  X displacy  

C:\Users\user>jupyter notebook  
[I 10:47:20.171 NotebookApp] Serving notebooks from local directory: C:\Users\user
[I 10:47:20.171 NotebookApp] 0 active kernels
[I 10:47:20.171 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=d8ab7d5c857f27e5f09cd60109335613d6bb46e161a4a364
[I 10:47:20.171 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).  
[C 10:47:20.181 NotebookApp]  

    Copy/paste this URL into your browser when you connect for the first time, to login with a token:  
        http://localhost:8888/?token=d8ab7d5c857f27e5f09cd60109335613d6bb46e161a4a364  
[I 10:47:20.605 NotebookApp] Accepting one-time-token-authenticated connection from ::1  
[I 10:47:25.328 NotebookApp] Creating new notebook in  
[W 10:47:25.980 NotebookApp] 404 GET /nbextensions/displacy.js?v=20170510104718  
(::1) 16.00ms referer=http://localhost:8888/notebooks/Untitled2.ipynb?kernel_name=python3  
[I 10:47:26.187 NotebookApp] Kernel started: b053144b-164c-4d82-a92d-451b7abd1b2f  
[W 10:47:26.324 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension  
.js?v=20170510104718 (::1) 8.00ms referer=http://localhost:8888/notebooks/Untitled2.ipynb? 
 kernel_name=python3
</details>

I'm on Win 7 64bit.

**Comment by ines** [comment]
Thanks for the update – and sorry about that!
Maybe this is a Windows thing or something related to a Jupyter update? I'll test this again and add a note to the docs in the meantime with the alternative solution.
