### ISSUE TITLE
How long should the wiki2txt.py step last?

### ISSUE THREAD

**Issue by xiapoy** [explosion/spacy-dev-resources#16]
I'm following this [tutorial](https://github.com/explosion/spacy-dev-resources/tree/master/vocab) to build the vocabulary.

During the process `fab -f vocab/fabfile build_wiki_vocab:<lang>`, the step running the script `wiki2txt.py` is quite long. It shows me an output with number of iterations (currently 150K iterations after 4h). Do you know how long this step should last?

**Comment by oroszgy** [comment]
It really depends on the size of the Wikipedia you are processing. If you want gain some speed (and don't care to much about the corpus quality set the `cleaned` parameter to `False` or comment out the 32th line.
