### ISSUE TITLE
Dev tools out of date?

### ISSUE THREAD

**Issue by eric41** [explosion/spacy-dev-resources#17]
Hi!

I'm trying to add a new language to spaCy, but I'm running into several errors when running the [training/init.py](https://github.com/explosion/spacy-dev-resources/blob/master/training/init.py#L70). First I ran into:
```
freq, doc_freq, key = line.rstrip().split('\t', 2)
ValueError: need more than 2 values to unpack
```
And indeed, the lines in the freqs file are as follows:
```
freq   word1
freq   word2
```
No document frequency in there. If I remove the `doc_freq` variable, nothing important seems to break in that part of code (only the removal of the minimum doc frequency threshold). I also removed the `literal_eval`, since I haven't filtered out special characters properly yet so this gave some errors otherwise.

However, now I'm running into the following error:
```
(u'Reading vocab from ', PosixPath('/outside/data/word_vectors.dat'))
Traceback (most recent call last):
  File "spacy-dev-resources/training/init.py", line 155, in <module>
    plac.call(main)
  File "/usr/local/lib/python2.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python2.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "spacy-dev-resources/training/init.py", line 151, in main
    write_vectors(vectors_loc, model_dir)
  File "spacy-dev-resources/training/init.py", line 119, in write_vectors
    write_binary_vectors(vectors_src.as_posix(), (dst_dir / 'vocab' / 'vec.bin').as_posix())
  File "spacy/vocab.pyx", line 666, in spacy.vocab.write_binary_vectors (spacy/vocab.cpp:13731)
  File "spacy/vocab.pyx", line 667, in spacy.vocab.write_binary_vectors (spacy/vocab.cpp:13448)
IOError: invalid data stream
```
Issue #2 seems to discuss the same issue, however the file I've got doesn't seem to be in the bzip2 format anyway, so of course it cannot open it as a bzip2 file. I can of course bzip2 it myself, but as shown in issue #2, the file will be read line by line and since the file starts with:
```
<80>^Bcgensim.models.word2vec
Word2Vec
```
And then a lot of 'gibberish' (maybe it's just a pickle file?), it wouldn't make sense to read this line by line.

I've created the `word_vectors.dat` file using the [training/word_vectors.py](https://github.com/explosion/spacy-dev-resources/blob/master/training/word_vectors.py#L92) file, which saves the model using the `.save()` function. If I look at the [gensim documentation for word2vec](https://radimrehurek.com/gensim/models/word2vec.html) I cannot really see an option to save the model in bzip2 format explicitly.

So, how should I be generating the required file? Since I'm obviously doing something wrong here. [The spaCy documentation](https://spacy.io/docs/usage/adding-languages#word-vectors) also states that the output file should be a readable 'binary' file:
> You can use our word vectors training script , which pre-processes the text with your language-specific tokenizer and trains the model using Gensim. The vectors.bin file should consist of one word and vector per line.

I ran the script in the following way, which has the minimal required arguments, I guess:
```
python spacy-dev-resources/training/word_vectors.py <languagecode> <input dir> /outside/data/word_vectors.dat
```

Thanks for taking the time to read this :)!

**Comment by oroszgy** [comment]
@eric41 You should checkout the `vocab` dir which could help you get started building a vocabulary from a corpus/wikipedia.

**Comment by eric41** [comment]
Thanks for the suggestion! 

If I manually run the [python -m gensim.scripts.word2vec_standalone](https://github.com/explosion/spacy-dev-resources/blob/master/vocab/fabfile/__init__.py#L112) module the resulting file is indeed in the format the [original training script](https://github.com/explosion/spacy-dev-resources/blob/master/training/init.py) can work with the generated output file. However, it doesn't seem to actually output a model.

So, conclusion, the dev tools are indeed out of date if you look at how they're referenced from the [spaCy documentation page](https://spacy.io/docs/usage/adding-languages). But luckily it also contains scripts to (presumably) create a proper vocabulary. How can we make sure the documentation is updated to point to these new scripts?

I'll look into your scripts and try the wikipedia example. I'll let you know if I run into any issues, otherwise I'll have a look at how to replace the wikipedia corpus with my own. Should be doable :)
