### ISSUE TITLE
expecteed vectors.bz2 content? 

### ISSUE THREAD

**Issue by trungtv** [explosion/spacy-dev-resources#2]
Hello,
Could you please elaborate more on the expected format for the vectors.bz2 as input for init.py. I tried to zip the output .bin of gensim model.save_word2vec_format() but it doesn't work. Here is the output:
`Traceback (most recent call last):
  File "init.py", line 162, in <module>
    plac.call(main)
  File "/Users/trungtv/anaconda2/lib/python2.7/site-packages/plac_core.py", line 326, in call
    cmd, result = parser_from(obj).consume(arglist)
  File "/Users/trungtv/anaconda2/lib/python2.7/site-packages/plac_core.py", line 209, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "init.py", line 158, in main
    write_vectors(vectors_loc, model_dir)
  File "init.py", line 126, in write_vectors
    write_binary_vectors(vectors_src.as_posix(), (dst_dir / 'vec.bin').as_posix())
  File "spacy/vocab.pyx", line 565, in spacy.vocab.write_binary_vectors (spacy/vocab.cpp:12178)
  File "spacy/vocab.pyx", line 568, in spacy.vocab.write_binary_vectors (spacy/vocab.cpp:11941)
IndexError: pop from empty list
`

**Comment by honnibal** [comment]
Hey,

Sure thing. Here's the code of `write_binary_vectors` for reference:

```python

def write_binary_vectors(in_loc, out_loc):
    cdef CFile out_file = CFile(out_loc, 'wb')
    cdef Address mem
    cdef int32_t word_len
    cdef int32_t vec_len
    cdef char* chars
    with bz2.BZ2File(in_loc, 'r') as file_:
        for line in file_:
            pieces = line.split()
            word = pieces.pop(0)
            mem = Address(len(pieces), sizeof(float))
            vec = <float*>mem.ptr
            for i, val_str in enumerate(pieces):
                vec[i] = float(val_str)

            word_len = len(word)
            vec_len = len(pieces)

            out_file.write_from(&word_len, 1, sizeof(word_len))
            out_file.write_from(&vec_len, 1, sizeof(vec_len))

            chars = <char*>word
            out_file.write_from(chars, len(word), sizeof(char))
            out_file.write_from(vec, vec_len, sizeof(float))
```

So:

* BZ2File
* Iterate over lines (so, newline delimited)
* `pieces = line.split()` --- This splits on all sequences of whitespace.
* `word = pieces.pop(0)` Get the first whitespace-delimited chunk
* Read rest as floats

It looks to me like the function doesn't handle trailing newlines properly, which is a pain, but there you go =/. Try making sure there are no empty lines in your file.

**Comment by trungtv** [comment]
Tks,
I got it. My vectors.bin contains vector for '\n'.
