### ISSUE TITLE
Creating my own model

### ISSUE THREAD

**Issue by oximer** [explosion/spacy-dev-resources#21]
Hey guys,

I'm trying to create new on Model and I'm having some trouble.

I'm basically trying to follow this [link](https://spacy.io/docs/usage/adding-languages#model-directory) and i'm using this [repo](https://github.com/explosion/spacy-dev-resources/blob/master/training)

`
python -m spacy model pt myModel portuguese/word_freq '' portuguese/word_vector.bz2
`

however I'm having trouble to generate vector.bin

>  File "/Users/urbano/Documents/fontes/spacy_18/spaCy/.env/lib/python2.7/site-packages/spacy-1.8.2-py2.7-macosx-10.11-x86_64.egg/spacy/cli/model.py", line 47, in create_model
>     write_binary_vectors(vectors_path.as_posix(), vectors_dest.as_posix())
>   File "spacy/vocab.pyx", line 672, in spacy.vocab.write_binary_vectors (spacy/vocab.cpp:14452)
>   File "spacy/vocab.pyx", line 681, in spacy.vocab.write_binary_vectors (spacy/vocab.cpp:14319)
> ValueError: could not convert string to float: train_countqKU

Here it is my files. One mini sample data, the word frequency that I generated and a word vector that I did using this [code](https://github.com/explosion/spacy-dev-resources/blob/master/training/word_vectors.py)

Files used to reproduce this error
[sample.zip](https://github.com/explosion/spacy-dev-resources/files/1118137/sample.zip)

**Comment by oroszgy** [comment]
Hi, take a look at the `vocab/fabfile` directory which might give you some hints on building a word2vec model.
