### ISSUE TITLE
Getting errors while creating Telugu spacy model

### ISSUE THREAD

**Issue by mdp0999** [explosion/spacy-dev-resources#25]
Hi everyone,
                   I am getting errors while creating a spaCy model according to the readme file in vocab. Here is the error:

mdp@mdp-Inspiron-N5110:~/spacy-dev-resources-master$ python -m spacy model te ./data/model/te/spacy_model ./data/model/te/te_wiki.freqs ./data/model/te/brown/paths ./data/model/te/te_wiki.word2vec.bz2

    Unknown command: model
    Available: profile, vocab, evaluate, train, link, download, validate,
    info, convert, package, init-model

Please help me at this step for creating spacy model

**Comment by mosynaq** [comment]
Refer to #24.

**Comment by azarezade** [comment]
In the new version of spacy you should use `init-model` instead of 'mode'. 
```
python -m spacy model te ./data/model/te/spacy_model ./data/model/te/te_wiki.freqs -c  ./data/model/te/brown/paths -v ./data/model/te/te_wiki.word2vec
```
Also use `-c` and '-v' for cluster and vectors path. 
And finally use `te_wiki.word2vec` instead of `te_wiki.word2vec.bz2`.
Refer to #28

**Comment by felixganz** [comment]
Hei @azarezade . I just try it, but I didn't get different result. I got this error:
![screen shot 2018-03-13 at 1 52 09 am](https://user-images.githubusercontent.com/24998545/37348360-797f5bda-2706-11e8-9fab-73015407106e.png)

can you help me with this error?

**Comment by azarezade** [comment]
Actually, this is a different error.
I don't exactly what is the problem here, you could inspect your data, and see what is stored in `counts` variable in the `init_model.py` file in `spacy/cli` folder.

**Comment by felixganz** [comment]
@azarezade  may I know your preshed libs version? I confused, in spacy-master required version 1.0.0 but in spacy-dev-resources required need version 0.46.4, witch one that I need to use? I think I got error because this library.

**Comment by azarezade** [comment]
I used 1.0.0 version, and it worked for me.
