### ISSUE TITLE
File "preshed/counter.pyx", line 73, in preshed.counter.GaleSmoother.__init__ (preshed/counter.cpp:2577) AssertionError: Cannot smooth your weird data

### ISSUE THREAD

**Issue by sigit-purnomo** [explosion/spacy-dev-resources#31]
As I want to train a new Word2Vec model for Indonesian (to add it to SpaCy), I got this error during training:

> File "preshed/counter.pyx", line 73, in preshed.counter.GaleSmoother.__init__ (preshed/counter.cpp:2577) AssertionError: Cannot smooth your weird data

Does anybody can help? Thank you

**Comment by alexhsieh53** [comment]
This error means that your don't have any words or phrases's count is 2 or 1. You should ensure your word have counts 1 or 2
