### ISSUE TITLE
Anyone attempted to build a complete Spacy model

### ISSUE THREAD

**Issue by omitobi** [explosion/spacy-dev-resources#32]
I realize there's no Finnish model in Spacy and I am wondering if there's any guide on how to build such model. I tried to follow this https://spacy.io/usage/adding-languages but I am quite new to NLP and Spacy. So is there an implementation already on going or is there a guide that I can follow step by step?

I need the Named Entity Recognition and word2Vector (to find similarities with words).

Thank you.

**Comment by bazzmx** [comment]
I'm on the process of building a catalan model, so far I'm at step one, I could not use wikipedia as corpus, python 3.6, nor my mac os python installation. 

So far I'm at step one with a small 10mb raw text corpus, I'm on step one currently on:

Merging phrase: 45771/50265: 45771(llaurador) [0.089s, cumulative 47m48.663s]

So there's lot of work pending. My advice to make things easier is to install anaconda, create a python 2.7 environment and use it to install all the requirements using pip, chances are openssl will raise exceptions, uninstall and reinstall if this happens. Then use raw text to create the vocabulary and the model.

I'll post back if this wor-----

Fatal error: local() encountered an error (return code 1) while executing 'python -m spacy model ca ././data/model/ca/vocab ./data/model/ca/ca_wiki.freqs ./data/model/ca/brown/paths ./data/model/ca/ca_wiki.word2vec.bz2'

Aborting.

nvm

**Comment by bazzmx** [comment]
Got everything working for catalan, you have to put some work but i managed to get the bare bones of a model working using all the universal dependencies data, follow the links to obtain all the data and get yourself a good machine for processing and model training and you'll get there:

 "accuracy":{
    "tags_acc":97.9993626288,
    "las":87.5971426329,
    "uas":90.7626187299,
    "token_acc":100.0,
    "ents_p":0.0,
    "ents_f":0.0,
    "ents_r":0.0
