### ISSUE TITLE
Scripts for Wikipedia language models

### ISSUE THREAD

**Issue by oroszgy** [explosion/spacy-dev-resources#4]
Currently, I am in the progress of creating Brown clusters, word freqs and word vectors for Hungarian from the Wikipedia dump. Would it be interesting to involve these scripts in this repository?

**Comment by ines** [comment]
Yes, absolutely – this would be great!

**Comment by Tpt** [comment]
@oroszgy I don't know if you now the Wikipedia search index dumps, they are great to create language models from Wikipedia: https://dumps.wikimedia.org/other/cirrussearch/current/ (all the wikitext markup is removed and templates are expended)

**Comment by oroszgy** [comment]
@Tpt Didn't know that, but sounds great!

**Comment by honnibal** [comment]
@Tpt That's amazing! Thanks!

**Comment by oroszgy** [comment]
@Tpt @honnibal Just checked the `cirrussearch` dumps, but I'd not recommend using them. For creating a **good** language model, you want to heavily filter your wiki corpus. For instance, I'd like to eliminate long lists, table contents and too short lines (sentences). As far as I see, this format is not suitable for that, since the `text` field contains everything without new line separators.

**Comment by oroszgy** [comment]
@ines #10
