### ISSUE TITLE
Loading vectors - exception ValueError?!

### ISSUE THREAD

**Issue by ecamaj** [explosion/spacy-dev-resources#6]
Adding new language, created vector file with word_vectors.py, everything seems ok on file level.
When trying to create Vocab with init.py, this error pops up on vectors part. 

```
  File "init.py", line 121, in write_vectors
    write_binary_vectors(vectors_src.as_posix(), (dst_dir / 'vec.bin').as_posix())
  File "spacy/vocab.pyx", line 565, in spacy.vocab.write_binary_vectors (spacy/vocab.cpp:12199)
  File "spacy/vocab.pyx", line 572, in spacy.vocab.write_binary_vectors (spacy/vocab.cpp:12067)
ValueError: could not convert string to float: b'c_codecs'
```

Any ideas?
Thanks!

**Comment by honnibal** [comment]
Hey,

Looks to me like the data file you're trying to load is incorrectly formatted. Do you have whitespace in the word that's keying that line?

Matt

**Comment by ecamaj** [comment]
It seems so.
Should Doc handle somehow these? 
doc = nlp(text) in word_vectors.py gives many "words" as spaces or similar.

When changed to this in Corpus in word_vectors (to skip those):
   ```
 def count_doc(self, doc):
        # Get counts for this document
        for word in doc:
            w = str(word).strip()
            if w != str(word):
                print("'"+str(word)+"'")
                continue
            self.counts.inc(word.orth, 1)
            self.strings[word.orth] = word
        return len(doc)
```

I get this in init.py:

  File "init.py", line 121, in write_vectors
    write_binary_vectors(vectors_src.as_posix(), (dst_dir / 'vec.bin').as_posix())
  File "spacy/vocab.pyx", line 565, in spacy.vocab.write_binary_vectors (spacy/vocab.cpp:12199)
  File "spacy/vocab.pyx", line 572, in spacy.vocab.write_binary_vectors (spacy/vocab.cpp:12067)
ValueError: could not convert string to float: b'\x86q'

**Comment by honnibal** [comment]
It looks like there are tokens with some sort of whitespace inside them. Maybe try `if len(word.split()) != 1` as a condition.

Agree this is unideal.

**Comment by ecamaj** [comment]
Added if len(str(word).split()) != 1 but now some other valueError.

`ValueError: could not convert string to float: b'K\x04X\x06\x00\x00\x00sampleq'`

What is interesting, I don't know what this string is.
Google:
\x00 (0x00) = NULL
\x04 (0x04) = EOT (End of transmission)
\x06 (0x06) = ACK (Acknowledge)

P.S. have to add str() around word, otherwise gives
`AttributeError: 'spacy.tokens.token.Token' object has no attribute 'split'`

**Comment by ecamaj** [comment]
With this:

```
if not str(word).strip() or len(str(word).split()) != 1:
    print("'"+str(word)+"'")
    continue
```

gives:

`ValueError: could not convert string to float: b'\x00\x00\x00null_wordq\x03K\x00X\x08\x00\x00\x00__scipysq\x04]q\x05X\x02\x00\x00\x00sgq\x06K\x00X\x04\x00\x00\x00loadq\x07cgensim.utils'`

**Comment by ecamaj** [comment]
Maybe its something with bz2?
After running word_vectors.py it creates some file which I compress with:
`bzip2 -z <file>`
because init.py expects .bz2 file.

?

**Comment by ecamaj** [comment]
OK, I think I found it.
word_vectors.py uses word2.vec for saving model, and it is using utils.py "save" method that does pickle.dump.

On the other hand, init.py uses "write_vectors" method which calls "write_binary_vectors" in vocab.pyx that uses bz2 and simply iterates over lines:

```
with bz2.BZ2File(in_loc, 'r') as file_:
        for line in file_:
```

So, it is obviously not intended to be used like that. But following https://spacy.io/docs/usage/adding-languages, I didn't catch that it should be used in some specific manner except running word_vectors.py and init.py (plus Brown clusters), so either the instructions are not correct or I missed some key element in between.

**Comment by ecamaj** [comment]
This handles problems (add this to word_vectors.py):

```
def export_for_spacy_vocab_init(word2vec_model, location):
    string = ""

    for word, vocab in word2vec_model.vocab.items():
        string += word + " " + " ".join(str(x) for x in word2vec_model[word].tolist()) + "\n"

    with bz2.open(location, "wt") as bz2_file:
        bz2_file.write(string)
```

and add this to the bottom of "main" method:

`export_for_spacy_vocab_init(model, out_loc)`
