### ISSUE TITLE
AttributeError: 'preshed.counter.PreshCounter' object has no attribute 'items' (in training/word_vectors.py)

### ISSUE THREAD

**Issue by raphael0202** [explosion/spacy-dev-resources#7]
As I want to train a new Word2Vec model for French (to add it to SpaCy), I got this error during training.
It seems indeed that PreshCounter does not have a items attribute, but we can easily get a (key, value) tuple by iterating over it (https://github.com/explosion/preshed/blob/master/preshed/counter.pyx).

**Comment by honnibal** [comment]
Thanks.

I'll fix this in the `PreshCounter`
